using System.CodeDom.Compiler;
using System.Text;
using DangFugBixs.Generators.Models;
using DangFugBixs.Generators.Utils;

namespace DangFugBixs.Generators.Emitters;

public static class RegistrationEmitter {
    public static string GenerateSource(IEnumerable<ServiceInfo> services) {
        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter, "    ");
        
        // 1. Header 
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("// Generated by NhemDangFugBixs.Tooling");
        writer.WriteLine("using VContainer;");
        writer.WriteLine("using VContainer.Unity;");
        writer.WriteLine();
        
        using (writer.Block("namespace NhemDangFugBixs.Generated")) {
            using (writer.Block("public static class VContainerRegistration")) {
                
                var groups = services.GroupBy(s => s.ScopeName);

                foreach (var group in groups) {
                    // Tên hàm sẽ động: RegisterGlobal, RegisterGameplay...
                    string methodName = $"Register{group.Key}"; 
                    
                    using (writer.Block($"public static void {methodName}(IContainerBuilder builder)")) {
                        foreach (var svc in group) {
                            string fullName = string.IsNullOrEmpty(svc.Namespace) 
                                ? svc.ClassName 
                                : $"{svc.Namespace}.{svc.ClassName}";
                            
                            writer.WriteLine($"builder.Register<{fullName}>(Lifetime.{svc.Lifetime});");
                        }
                    }
                    writer.WriteLine(); // Xuống dòng giữa các hàm cho đẹp
                }
            }
        }
        return stringWriter.ToString();
    }
}