using System.CodeDom.Compiler;
using System.Text;
using DangFugBixs.Generators.Models;
using DangFugBixs.Generators.Utils;

namespace DangFugBixs.Generators.Emitters;

public static class RegistrationEmitter {
    public static string GenerateSource(IEnumerable<ServiceInfo> services) {
        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter, "    ");
        
        // 1. Header 
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("// Generated by NhemDangFugBixs.Tooling");
        writer.WriteLine("using VContainer;");
        writer.WriteLine("using VContainer.Unity;");
        writer.WriteLine();

        using (writer.Block("namespace NhemDangFugBixs.Generated")) {
            using (writer.Block("public static class VContainerRegistration")) {
                using (writer.Block("public static void RegisterAll(IContainerBuilder builder)")) {
                    foreach (var svc in services) {
                        string fullName = string.IsNullOrEmpty(svc.Namespace) 
                            ? svc.ClassName 
                            : $"{svc.Namespace}.{svc.ClassName}";
                        
                        writer.WriteLine($"builder.Register<{fullName}>(Lifetime.{svc.Lifetime});");                    }
                }
            }
        }
        
        return stringWriter.ToString();
    }
}