using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NhemDangFugBixs.Common.Models;
using NhemDangFugBixs.Generators.Utils;

namespace NhemDangFugBixs.Generators.Emitters;

internal static class RegistrationEmitter {
    public static string GenerateSource(
        IEnumerable<ServiceInfo> services,
        IEnumerable<SceneInjectionInfo> sceneServices,
        string assemblyName,
        List<ScopeMappingInfo> scopeMappings = null,
        GenerationStats? stats = null) {
        string sanitizedAssemblyName = SanitizeNamespace(assemblyName);

        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        writer.WriteLine("// <auto-generated />");
        if (stats != null) {
            writer.WriteLine($"// Generated by NhemDangFugBixs.Tooling {stats.Version}");
            writer.WriteLine($"// Date: {stats.Timestamp}");
            writer.WriteLine($"// Services: {stats.ServiceCount} registered");
            if (stats.Warnings.Count > 0) {
                writer.WriteLine("// Warnings:");
                foreach (var warning in stats.Warnings) {
                    writer.WriteLine($"// - {warning}");
                }
            }
        }
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using VContainer;");
        writer.WriteLine("using VContainer.Unity;");
        writer.WriteLine();

        var filteredGroups = BuildGroups(services, scopeMappings, sanitizedAssemblyName, out var installerModels);

        EmitExtensionsNamespace(writer, scopeMappings ?? new List<ScopeMappingInfo>(), installerModels);
        writer.WriteLine();
        EmitGeneratedNamespace(writer, sanitizedAssemblyName, sceneServices, filteredGroups, installerModels);

        return stringWriter.ToString();
    }

    private static Dictionary<string, List<ServiceInfo>> BuildGroups(
        IEnumerable<ServiceInfo> services,
        List<ScopeMappingInfo>? scopeMappings,
        string generatedNamespace,
        out List<InstallerModel> installerModels) {
        var distinctServices = services
            .GroupBy(s => s.FullName, System.StringComparer.Ordinal)
            .Select(group => group.First());

        var mappedServices = distinctServices.Select(service => MapServiceToInstallerScope(service, scopeMappings));
        var rawGroups = mappedServices
            .GroupBy(service => GetScopeKey(service), System.StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.ToList(), System.StringComparer.Ordinal);

        var assigned = new HashSet<string>(System.StringComparer.Ordinal);
        var filteredGroups = new Dictionary<string, List<ServiceInfo>>(System.StringComparer.Ordinal);
        foreach (var kvp in rawGroups.OrderBy(pair => pair.Key, System.StringComparer.Ordinal)) {
            var groupServices = new List<ServiceInfo>();
            foreach (var service in kvp.Value) {
                if (assigned.Add(service.FullName)) {
                    groupServices.Add(service);
                }
            }

            if (groupServices.Count > 0) {
                filteredGroups[kvp.Key] = groupServices;
            }
        }

        installerModels = filteredGroups
            .Select(kvp => CreateInstallerModel(kvp.Key, kvp.Value, scopeMappings, generatedNamespace))
            .OrderBy(model => model.ScopeKey, System.StringComparer.Ordinal)
            .ToList();

        return filteredGroups;
    }

    private static void EmitExtensionsNamespace(
        IndentedTextWriter writer,
        List<ScopeMappingInfo> scopeMappings,
        List<InstallerModel> installerModels) {
        using (writer.Block("namespace NhemDangFugBixs.VContainer")) {
            using (writer.Block("public static partial class NhemGeneratedVContainerExtensions")) {
                using (writer.Block("public static void RegisterGeneratedFor<TScope>(this global::VContainer.IContainerBuilder builder)")) {
                    writer.WriteLine("if (builder == null) throw new global::System.ArgumentNullException(nameof(builder));");
                    writer.WriteLine("var marker = typeof(TScope);");
                    foreach (var installer in installerModels.Where(model => model.MarkerTypeName != null)) {
                        writer.WriteLine($"if (marker == typeof(global::{installer.MarkerTypeName})) {{ global::NhemDangFugBixs.Generated.{installer.GeneratedNamespace}.{installer.InstallerClassName}.Register(builder); return; }}");
                    }
                    writer.WriteLine("throw new global::System.InvalidOperationException($\"No generated VContainer installer found for scope marker {marker.FullName}.\");");
                }
            }
        }
    }

    private static void EmitGeneratedNamespace(
        IndentedTextWriter writer,
        string sanitizedAssemblyName,
        IEnumerable<SceneInjectionInfo> sceneServices,
        Dictionary<string, List<ServiceInfo>> filteredGroups,
        List<InstallerModel> installerModels) {
        using (writer.Block($"namespace NhemDangFugBixs.Generated.{sanitizedAssemblyName}")) {
            writer.WriteLine();
            using (writer.Block("public static partial class SceneInjectionBlueprint")) {
                writer.WriteLine("public static readonly global::System.Type[] ComponentTypes = {");
                writer.Indent++;
                foreach (var svc in sceneServices.GroupBy(s => s.FullName, System.StringComparer.Ordinal).Select(g => g.First())) {
                    writer.WriteLine($"typeof(global::{svc.FullName}),");
                }
                writer.Indent--;
                writer.WriteLine("};");
            }
            writer.WriteLine();

            foreach (var installer in installerModels) {
                EmitInstaller(writer, installer);
                writer.WriteLine();
            }

            EmitCompatibilityFacade(writer, installerModels);
        }
    }

    private static void EmitInstaller(IndentedTextWriter writer, InstallerModel installer) {
        using (writer.Block($"public static partial class {installer.InstallerClassName}")) {
            using (writer.Block("public static void Register(global::VContainer.IContainerBuilder builder)")) {
                writer.WriteLine("if (builder == null) throw new global::System.ArgumentNullException(nameof(builder));");
                writer.WriteLine("RegisterServices(builder);");
                writer.WriteLine("RegisterEntryPoints(builder);");
                writer.WriteLine("RegisterComponents(builder);");
            }
            writer.WriteLine();

            using (writer.Block("private static void RegisterServices(global::VContainer.IContainerBuilder builder)")) {
                EmitRegistrations(writer, installer.Services);
            }
            writer.WriteLine();

            using (writer.Block("private static void RegisterEntryPoints(global::VContainer.IContainerBuilder builder)")) {
                EmitRegistrations(writer, installer.EntryPoints);
            }
            writer.WriteLine();

            using (writer.Block("private static void RegisterComponents(global::VContainer.IContainerBuilder builder)")) {
                EmitRegistrations(writer, installer.Components);
            }
        }
    }

    private static void EmitCompatibilityFacade(IndentedTextWriter writer, List<InstallerModel> installerModels) {
        using (writer.Block("public static partial class VContainerRegistration")) {
            using (writer.Block("public static void RegisterAll(global::VContainer.IContainerBuilder builder)")) {
                foreach (var installer in installerModels) {
                    writer.WriteLine($"{installer.InstallerClassName}.Register(builder);");
                }
            }
            writer.WriteLine();

            using (writer.Block("public static void RegisterGeneratedFor<TScopeMarker>(global::VContainer.IContainerBuilder builder)")) {
                writer.WriteLine("global::NhemDangFugBixs.VContainer.NhemGeneratedVContainerExtensions.RegisterGeneratedFor<TScopeMarker>(builder);");
            }
            writer.WriteLine();

            foreach (var installer in installerModels) {
                using (writer.Block($"public static void {installer.LegacyMethodName}(global::VContainer.IContainerBuilder builder)")) {
                    writer.WriteLine($"{installer.InstallerClassName}.Register(builder);");
                }
                writer.WriteLine();

                if (installer.MarkerTypeName != null) {
                    var markerSimpleName = GetSimpleName(installer.MarkerTypeName);
                    using (writer.Block($"public static void RegisterGeneratedFor{SanitizeIdentifier(markerSimpleName)}(global::VContainer.IContainerBuilder builder)")) {
                        writer.WriteLine($"{installer.InstallerClassName}.Register(builder);");
                    }
                    writer.WriteLine();
                }
            }
        }
    }

    private static void EmitRegistrations(IndentedTextWriter writer, IReadOnlyList<ServiceInfo> services) {
        if (services.Count == 0) {
            return;
        }

        foreach (var svc in services) {
            EmitRegistration(writer, svc);
        }
    }

    private static void EmitRegistration(IndentedTextWriter writer, ServiceInfo svc) {
        string fullName = $"global::{svc.FullName}";
        string lifetime = $"global::VContainer.Lifetime.{svc.Lifetime}";
        string keyed = GetKeyedSuffix(svc);

        if (svc.IsInstaller) {
            writer.WriteLine($"new {fullName}().Install(builder);");
            return;
        }

        if (svc.RegisterInHierarchy || (svc.Metadata.TryGetValue("ComponentMode", out var mode) && mode == "Hierarchy")) {
            string suffix = GetSmartSuffix(svc);
            writer.WriteLine($"builder.RegisterComponentInHierarchy<{fullName}>(){keyed}{suffix};");
            return;
        }

        if (svc.IsComponent) {
            string suffix = GetSmartSuffix(svc);
            if (svc.Metadata.TryGetValue("GameObjectName", out var gameObjectName) && !string.IsNullOrWhiteSpace(gameObjectName)) {
                writer.WriteLine($"builder.RegisterComponentOnNewGameObject<{fullName}>({lifetime}, \"{EscapeString(gameObjectName)}\"){keyed}{suffix};");
            } else {
                writer.WriteLine($"builder.RegisterComponentOnNewGameObject<{fullName}>({lifetime}){keyed}{suffix};");
            }
            return;
        }

        if (svc.IsMessagePipeBroker) {
            string messageType = svc.MessageType != null ? $"global::{svc.MessageType}" : fullName;
            writer.WriteLine($"builder.RegisterMessageBroker<{messageType}>({lifetime}){keyed};");
            return;
        }

        if (svc.IsFactory) {
            string suffix = GetSmartSuffix(svc);
            writer.WriteLine($"builder.RegisterFactory<{fullName}>(c => () => c.Resolve<{fullName}>(), {lifetime}){keyed}{suffix};");
            return;
        }

        if (svc.IsEntryPoint) {
            string suffix = GetSmartEntryPointSuffix(svc);
            writer.WriteLine($"builder.RegisterEntryPoint<{fullName}>(){keyed}{suffix};");
            return;
        }

        writer.WriteLine($"builder.Register<{fullName}>({lifetime}){keyed}{GetSmartSuffix(svc)};");
    }

    private static string GetKeyedSuffix(ServiceInfo svc) {
        if (svc.Metadata.TryGetValue("KeyedExpression", out var keyExpr) && !string.IsNullOrWhiteSpace(keyExpr)) {
            return $".Keyed({keyExpr})";
        }

        return string.Empty;
    }

    private static string GetSmartSuffix(ServiceInfo svc) {
        if (svc.AsTypes != null && svc.AsTypes.Length > 0) {
            return string.Concat(svc.AsTypes.Select(t => $".As<global::{t}>()")) + (svc.AsSelf ? ".AsSelf()" : string.Empty);
        }

        var suffix = string.Empty;
        bool shouldBindImplementedInterfaces = svc.AsImplementedInterfaces || (svc.IsComponent && svc.IsEntryPoint);
        if (shouldBindImplementedInterfaces) suffix += ".AsImplementedInterfaces()";
        if (svc.AsSelf) suffix += ".AsSelf()";
        return suffix;
    }

    private static string GetSmartEntryPointSuffix(ServiceInfo svc) {
        if (svc.AsTypes != null && svc.AsTypes.Length > 0) {
            return string.Concat(svc.AsTypes.Select(t => $".As<global::{t}>()")) + (svc.AsSelf ? ".AsSelf()" : string.Empty);
        }

        var customInterfaces = svc.InterfaceNames
            .Where(i => !InterfaceUtils.IsVContainerEntryPoint(i))
            .ToList();

        if (customInterfaces.Count > 0) {
            var suffix = string.Concat(customInterfaces.Select(i => $".As<global::{i}>()"));
            if (svc.AsSelf) {
                suffix += ".AsSelf()";
            }
            return suffix;
        }

        return svc.AsSelf ? ".AsSelf()" : string.Empty;
    }

    private static ServiceInfo MapServiceToInstallerScope(ServiceInfo service, List<ScopeMappingInfo>? scopeMappings) {
        if (service.UsesTypeSafeScope && !string.IsNullOrEmpty(service.ScopeTypeName) && scopeMappings != null) {
            var mapping = scopeMappings.FirstOrDefault(m => m.IdentityTypeName == service.ScopeTypeName);
            if (!string.IsNullOrEmpty(mapping.IdentityTypeName)) {
                return new ServiceInfo(
                    service.Namespace, service.ClassName, service.Lifetime, mapping.IdentityTypeName,
                    service.InterfaceNames, service.IsComponent, service.AsImplementedInterfaces,
                    service.AsSelf, service.RegisterInHierarchy, service.AsTypes, service.IsEntryPoint,
                    service.IsFactory, mapping.IdentityTypeName, true, service.IsExceptionHandler, service.IsBuildCallback,
                    service.IsInstaller, service.InstallerOrder, service.IsMessagePipeBroker, service.MessageType, service.MessagePipeKind, service.Metadata);
            }
        }

        return service;
    }

    private static string GetScopeKey(ServiceInfo service) {
        if (service.UsesTypeSafeScope && !string.IsNullOrEmpty(service.ScopeTypeName)) {
            return service.ScopeTypeName;
        }

        return service.ScopeName;
    }

    private static InstallerModel CreateInstallerModel(string scopeKey, List<ServiceInfo> services, List<ScopeMappingInfo>? scopeMappings, string generatedNamespace) {
        ScopeMappingInfo? matchedMapping = null;
        if (scopeMappings != null) {
            foreach (var mapping in scopeMappings) {
                if (mapping.IdentityTypeName == scopeKey || mapping.AliasName == scopeKey || mapping.ClassName == scopeKey) {
                    matchedMapping = mapping;
                    break;
                }
            }
        }

        var markerTypeName = matchedMapping?.IdentityTypeName;

        string scopeStem = GetInstallerStem(markerTypeName ?? scopeKey);
        string installerClassName = $"NhemGenerated{scopeStem}Installer";
        var legacyScopeName = matchedMapping?.AliasName ?? matchedMapping?.ClassName ?? scopeKey;
        return new InstallerModel(
            scopeKey,
            installerClassName,
            GetLegacyMethodName(legacyScopeName),
            markerTypeName,
            generatedNamespace,
            services.Where(s => !s.IsComponent && !s.IsEntryPoint && !s.IsExceptionHandler && !s.IsBuildCallback).OrderBy(s => s.ClassName, System.StringComparer.Ordinal).ToList(),
            services.Where(s => s.IsEntryPoint && !s.IsExceptionHandler && !s.IsBuildCallback).OrderBy(s => s.ClassName, System.StringComparer.Ordinal).ToList(),
            services.Where(s => s.IsComponent).OrderBy(s => s.ClassName, System.StringComparer.Ordinal).ToList(),
            new List<ServiceInfo>());
    }

    private static string GetLegacyMethodName(string scopeKey) {
        string name = GetSimpleName(scopeKey);
        if (name.EndsWith("LifetimeScope", System.StringComparison.Ordinal)) {
            name = name.Substring(0, name.Length - "LifetimeScope".Length);
        }

        if (string.IsNullOrEmpty(name)) {
            name = "Global";
        }

        return $"Register{name}";
    }

    private static string GetInstallerStem(string scopeKey) {
        var simpleName = GetSimpleName(scopeKey);
        if (simpleName.StartsWith("I", System.StringComparison.Ordinal) &&
            simpleName.Length > 1 &&
            char.IsUpper(simpleName[1])) {
            simpleName = simpleName.Substring(1);
        }

        if (!simpleName.EndsWith("Scope", System.StringComparison.Ordinal)) {
            simpleName += "Scope";
        }

        return SanitizeIdentifier(simpleName);
    }

    private static string GetSimpleName(string fullName) {
        return fullName.Contains(".") ? fullName.Split('.').Last() : fullName;
    }

    private static string SanitizeIdentifier(string value) {
        var chars = value.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray();
        return new string(chars);
    }

    private static string SanitizeNamespace(string assemblyName) {
        return new string(assemblyName.Select(c => char.IsLetterOrDigit(c) || c == '.' ? c : '_').ToArray()).Replace(".", "_");
    }

    private static string EscapeString(string value) {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed class InstallerModel {
        public InstallerModel(
            string scopeKey,
            string installerClassName,
            string legacyMethodName,
            string? markerTypeName,
            string generatedNamespace,
            List<ServiceInfo> services,
            List<ServiceInfo> entryPoints,
            List<ServiceInfo> components,
            List<ServiceInfo> callbacks) {
            ScopeKey = scopeKey;
            InstallerClassName = installerClassName;
            LegacyMethodName = legacyMethodName;
            MarkerTypeName = markerTypeName;
            GeneratedNamespace = generatedNamespace;
            Services = services;
            EntryPoints = entryPoints;
            Components = components;
            Callbacks = callbacks;
        }

        public string ScopeKey { get; }
        public string InstallerClassName { get; }
        public string LegacyMethodName { get; }
        public string? MarkerTypeName { get; }
        public string GeneratedNamespace { get; }
        public List<ServiceInfo> Services { get; }
        public List<ServiceInfo> EntryPoints { get; }
        public List<ServiceInfo> Components { get; }
        public List<ServiceInfo> Callbacks { get; }
    }
}
