using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.IO;
using NhemDangFugBixs.Common.Models;
using NhemDangFugBixs.Generators.Utils;

namespace NhemDangFugBixs.Generators.Emitters;

internal static class RegistrationEmitter {
    public static string GenerateSource(
        IEnumerable<ServiceInfo> services,
        IEnumerable<SceneInjectionInfo> sceneServices,
        string assemblyName,
        List<ScopeMappingInfo> scopeMappings = null) {

        // Improved sanitization: replace any non-alphanumeric with underscore but keep dots for stable hint names
        string sanitizedNamespace = new string(assemblyName.Select(c => char.IsLetterOrDigit(c) || c == '.' ? c : '_').ToArray()).Replace("..", ".");

        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        // 1. Header - Global usings must be at the very top
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("// Generated by NhemDangFugBixs.Tooling v3.2");
        writer.WriteLine("// Robust indestructible C# emission");
        writer.WriteLine();
        writer.WriteLine("// Global alias for convenience");
        writer.WriteLine("global using NLifetime = global::NhemDangFugBixs.Attributes.NhemLifetime;");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine();

        using (writer.Block($"namespace NhemDangFugBixs.Generated.{sanitizedNamespace.Replace(".", "_")}")) {

            // 1. Blueprint for Editor Discovery (Scene Injection)
            using (writer.Block("public static partial class SceneInjectionBlueprint")) {
                writer.WriteLine("public static readonly global::System.Type[] ComponentTypes = {");
                writer.Indent++;
                // Deduplicate scene services by full name
                foreach (var svc in sceneServices.GroupBy(s => s.FullName).Select(g => g.First())) {
                    writer.WriteLine($"typeof(global::{svc.FullName}),");
                }
                writer.Indent--;
                writer.WriteLine("};");
            }
            writer.WriteLine();

            // 2. Standard VContainer Registrations
            using (writer.Block("public static partial class VContainerRegistration")) {

                // MASTER ENTRY POINT (v3.1)
                if (scopeMappings != null && scopeMappings.Count > 0) {
                    using (writer.Block("public static void RegisterAll(global::VContainer.IContainerBuilder builder)")) {
                        foreach (var mapping in scopeMappings) {
                            string methodName = GetRegistrationMethodName(mapping.ClassName);
                            writer.WriteLine($"{methodName}(builder);");
                        }
                    }
                    writer.WriteLine();
                }

                // Deduplicate services by full name to prevent double-registration conflicts
                var distinctServices = services.GroupBy(s => $"{s.Namespace}.{s.ClassName}").Select(g => g.First());

                // Group services by their scope key
                // Map services that use an Identity Type to the mapped Scope Type name
                var mappedServices = distinctServices.Select(s => {
                    if (s.UsesTypeSafeScope && scopeMappings != null) {
                        // 1. Try to match Identity Type
                        var mapping = scopeMappings.FirstOrDefault(m => m.IdentityTypeName == s.ScopeTypeName);
                        if (!string.IsNullOrEmpty(mapping.ClassName)) {
                            return MapToScope(s, mapping.ClassName);
                        }
                        
                        // 2. Try to match Scope Class Name itself (to pick up [ScopeName] overrides)
                        var directMapping = scopeMappings.FirstOrDefault(m => 
                            m.OriginalFullName == s.ScopeTypeName || 
                            m.OriginalClassName == s.ScopeTypeName ||
                            m.FullName == s.ScopeTypeName || 
                            m.ClassName == s.ScopeTypeName);
                            
                        if (!string.IsNullOrEmpty(directMapping.ClassName)) {
                            return MapToScope(s, directMapping.ClassName);
                        }
                    }
                    return s;
                });

                var groups = mappedServices.GroupBy(s => GetScopeKey(s)).ToDictionary(g => g.Key, g => g.ToList());

                foreach (var group in groups) {
                    string methodName = GetRegistrationMethodName(group.Key);

                    using (writer.Block($"public static void {methodName}(global::VContainer.IContainerBuilder builder)")) {
                        writer.WriteLine("global::VContainer.Unity.EntryPointsBuilder.EnsureDispatcherRegistered(builder);");

                        // Emit service registrations
                        foreach (var svc in group.Value) {
                            var suffix = "";

                            if (svc.AsTypes != null && svc.AsTypes.Length > 0) {
                                suffix += ".As(" + string.Join(", ", svc.AsTypes.Select(t => $"typeof(global::{t})")) + ")";
                            } else {
                                // If it's an entry point, AsImplementedInterfaces is already handled by RegisterEntryPoint
                                if (svc.AsImplementedInterfaces && !svc.IsEntryPoint) suffix += ".AsImplementedInterfaces()";
                                if (svc.AsSelf) suffix += ".AsSelf()";
                            }

                            string fullName = $"global::{svc.FullName}";

                            if (svc.RegisterInHierarchy) {
                                writer.WriteLine($"builder.RegisterComponentInHierarchy<{fullName}>(){suffix};");
                            } else if (svc.IsComponent) {
                                writer.WriteLine($"builder.RegisterComponentOnNewGameObject<{fullName}>(global::VContainer.Lifetime.{svc.Lifetime}){suffix};");
                            } else if (svc.IsFactory) {
                                writer.WriteLine($"builder.RegisterFactory<{fullName}>(c => () => c.Resolve<{fullName}>(), global::VContainer.Lifetime.{svc.Lifetime}){suffix};");
                            } else if (svc.IsEntryPoint) {
                                writer.WriteLine($"builder.RegisterEntryPoint<{fullName}>(global::VContainer.Lifetime.{svc.Lifetime}){suffix};");
                            } else {
                                writer.WriteLine($"builder.Register<{fullName}>(global::VContainer.Lifetime.{svc.Lifetime}){suffix};");
                            }
                        }
                    }
                    writer.WriteLine();
                }
            }
        }
        return stringWriter.ToString();
    }

    private static ServiceInfo MapToScope(ServiceInfo s, string targetScopeName) {
        return new ServiceInfo(
            s.Namespace, s.ClassName, s.Lifetime, s.ScopeName,
            s.InterfaceNames, s.IsComponent, s.AsImplementedInterfaces,
            s.AsSelf, s.RegisterInHierarchy, s.AsTypes, s.IsEntryPoint,
            s.IsFactory, targetScopeName, true);
    }

    /// <summary>
    /// Gets the grouping key for a service - either the scope type name (for type-safe) or scope name (legacy).
    /// </summary>
    private static string GetScopeKey(ServiceInfo service) {
        // For type-safe scopes, use the scope type name
        if (service.UsesTypeSafeScope && !string.IsNullOrEmpty(service.ScopeTypeName)) {
            return service.ScopeTypeName;
        }
        // Fallback to legacy scope name
        return service.ScopeName;
    }

    /// <summary>
    /// Generates the registration method name from a scope key.
    /// For type-safe scopes: strips "LifetimeScope" suffix (e.g., GameplayLifetimeScope → RegisterGameplay)
    /// For legacy scopes: uses the scope name directly (e.g., "Gameplay" → RegisterGameplay)
    /// </summary>
    private static string GetRegistrationMethodName(string scopeKey) {
        string name = scopeKey;
        
        // Strip namespace if present
        if (name.Contains(".")) {
            name = name.Split('.').Last();
        }

        // Check if this looks like a type name (ends with LifetimeScope)
        if (name.EndsWith("LifetimeScope", StringComparison.Ordinal)) {
            // Strip "LifetimeScope" suffix
            name = name.Substring(0, name.Length - "LifetimeScope".Length);
            // Handle edge case: if nothing left, use original
            if (string.IsNullOrEmpty(name)) {
                return "RegisterGlobal";
            }
        }
        
        return $"Register{name}";
    }
}
