using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using NhemDangFugBixs.Common.Models;

namespace NhemDangFugBixs.Generators.Emitters;

internal static class ReportEmitter {
    public static string GenerateMarkdown(IEnumerable<ServiceInfo> services, string assemblyName) {
        var serviceList = services.ToList();
        var sb = new StringBuilder();
        
        // Header
        sb.AppendLine($"# DI Registration Report - {assemblyName}");
        sb.AppendLine($"> Generated by NhemDangFugBixs.Tooling v5.2 on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Summary Statistics
        var grouped = serviceList.GroupBy(s => GetScopeKey(s)).OrderBy(g => g.Key);
        var entryPoints = serviceList.Where(s => s.IsEntryPoint).ToList();
        var messagePipeBrokers = serviceList.Where(s => s.IsMessagePipeBroker).ToList();
        var installers = serviceList.Where(s => s.IsInstaller).ToList();

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"| Metric | Count |");
        sb.AppendLine("| :--- | :---: |");
        sb.AppendLine($"| **Total Services** | {serviceList.Count} |");
        sb.AppendLine($"| **Total Scopes** | {grouped.Count()} |");
        sb.AppendLine($"| **Entry Points** | {entryPoints.Count} |");
        sb.AppendLine($"| **MessagePipe Brokers** | {messagePipeBrokers.Count} |");
        sb.AppendLine($"| **Installers** | {installers.Count} |");
        sb.AppendLine();

        // Scope Details
        foreach (var group in grouped) {
            var scopeName = group.Key;
            var scopeServices = group.ToList();
            var scopeEntryPoints = scopeServices.Where(s => s.IsEntryPoint).ToList();
            var scopeInstallers = scopeServices.Where(s => s.IsInstaller).ToList();

            sb.AppendLine($"## Scope: {scopeName}");
            sb.AppendLine();
            sb.AppendLine($"**Services:** {scopeServices.Count} | **Entry Points:** {scopeEntryPoints.Count} | **Installers:** {scopeInstallers.Count}");
            sb.AppendLine();
            sb.AppendLine("| Service | Lifetime | Type | Contracts | Entry Point |");
            sb.AppendLine("| :--- | :--- | :--- | :--- | :---: |");

            foreach (var svc in scopeServices.OrderBy(s => s.ClassName)) {
                string kind = GetServiceKind(svc);
                string contracts = GetContractsDisplay(svc);
                string entryPoint = svc.IsEntryPoint ? "✅" : "-";
                sb.AppendLine($"| {svc.ClassName} | {svc.Lifetime} | {kind} | {contracts} | {entryPoint} |");
            }
            sb.AppendLine();
        }

        // Entry Points Summary
        if (entryPoints.Count > 0) {
            sb.AppendLine("## Entry Points");
            sb.AppendLine();
            sb.AppendLine("| Service | Scope | Interfaces |");
            sb.AppendLine("| :--- | :--- | :--- |");
            foreach (var ep in entryPoints.OrderBy(e => e.ClassName)) {
                var scope = GetScopeKey(ep);
                var interfaces = ep.InterfaceNames.Length > 0 ? string.Join(", ", ep.InterfaceNames) : "-";
                sb.AppendLine($"| {ep.ClassName} | {scope} | {interfaces} |");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string GetContractsDisplay(ServiceInfo svc) {
        if (svc.AsTypes != null && svc.AsTypes.Length > 0) {
            var typeNames = svc.AsTypes.Select(t => {
                var parts = t.Split('.');
                return parts.Length > 0 ? parts.Last() : t;
            }).ToList();
            return string.Join(", ", typeNames);
        }

        if (svc.AsImplementedInterfaces && svc.InterfaceNames.Length > 0) {
            return "All Interfaces";
        }

        if (svc.AsSelf) {
            return "Self Only";
        }

        return "-";
    }

    public static string GenerateSource(IEnumerable<ServiceInfo> services, IEnumerable<RootLoggingInfo> rootLogging, string assemblyName) {
        var serviceList = services.ToList();
        var rootLoggingList = rootLogging.ToList();
        var markdown = GenerateMarkdown(serviceList, assemblyName);
        var serviceCount = serviceList.Count;
        var scopes = serviceList
            .Select(GetScopeKey)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(scope => scope, StringComparer.Ordinal)
            .ToList();
        var entries = serviceList
            .OrderBy(s => GetScopeKey(s), StringComparer.Ordinal)
            .ThenBy(s => s.FullName, StringComparer.Ordinal)
            .Select(service => EncodeEntry(service))
            .ToList();
        var consumers = serviceList
            .SelectMany(EncodeConsumers)
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToList();
        var loggerRoots = rootLoggingList
            .OrderBy(info => info.ScopeName, StringComparer.Ordinal)
            .Select(info => $"{info.ScopeName}|{info.HasLoggerFactory}|{info.HasLoggerAdapter}")
            .ToList();
        var loggerConsumers = serviceList
            .SelectMany(EncodeLoggerConsumers)
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace NhemDangFugBixs.Generated.{Sanitize(assemblyName)}");
        sb.AppendLine("{");
        sb.AppendLine("    public static class RegistrationReport");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const int ServiceCount = {serviceCount};");
        sb.AppendLine($"        public const int ScopeCount = {scopes.Count};");
        sb.AppendLine("        public static readonly string[] Scopes = new string[]");
        sb.AppendLine("        {");
        foreach (var scope in scopes) {
            sb.AppendLine($"            \"{Escape(scope)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] Entries = new string[]");
        sb.AppendLine("        {");
        foreach (var entry in entries) {
            sb.AppendLine($"            \"{Escape(entry)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] Consumers = new string[]");
        sb.AppendLine("        {");
        foreach (var consumer in consumers) {
            sb.AppendLine($"            \"{Escape(consumer)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] LoggerRoots = new string[]");
        sb.AppendLine("        {");
        foreach (var loggerRoot in loggerRoots) {
            sb.AppendLine($"            \"{Escape(loggerRoot)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] LoggerConsumers = new string[]");
        sb.AppendLine("        {");
        foreach (var loggerConsumer in loggerConsumers) {
            sb.AppendLine($"            \"{Escape(loggerConsumer)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public const string Markdown = @\"");
        sb.AppendLine(markdown.Replace("\"", "\"\""));
        sb.AppendLine("\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetServiceKind(ServiceInfo svc) {
        if (svc.IsMessagePipeBroker) return "MessageBroker";
        if (svc.IsComponent) return "Component";
        if (svc.IsEntryPoint) return "EntryPoint";
        if (svc.IsInstaller) return "Installer";
        if (svc.IsFactory) return "Factory";
        return "Standard";
    }

    private static string GetScopeKey(ServiceInfo service) {
        if (service.UsesTypeSafeScope && !string.IsNullOrEmpty(service.ScopeTypeName)) {
            return service.ScopeTypeName;
        }

        return service.ScopeName;
    }

    private static string EncodeEntry(ServiceInfo service) {
        return string.Join("|", [
            GetScopeKey(service),
            service.FullName,
            service.Lifetime,
            GetServiceKind(service),
            service.MessageType ?? string.Empty
        ]);
    }

    private static IEnumerable<string> EncodeConsumers(ServiceInfo service) {
        if (!service.Metadata.TryGetValue("MessagePipeConsumers", out var rawValue) || string.IsNullOrWhiteSpace(rawValue)) {
            yield break;
        }

        foreach (var consumer in rawValue.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)) {
            var parts = consumer.Split(new[] { ':' }, 2);
            if (parts.Length != 2) {
                continue;
            }

            yield return string.Join("|", [
                GetScopeKey(service),
                service.FullName,
                parts[0],
                parts[1]
            ]);
        }
    }

    private static IEnumerable<string> EncodeLoggerConsumers(ServiceInfo service) {
        if (!service.Metadata.TryGetValue("LoggerConsumers", out var rawValue) || string.IsNullOrWhiteSpace(rawValue)) {
            yield break;
        }

        foreach (var consumer in rawValue.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)) {
            yield return string.Join("|", [
                GetScopeKey(service),
                service.FullName,
                consumer
            ]);
        }
    }

    private static string Escape(string value) {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string Sanitize(string assemblyName) {
        return new string(assemblyName.Select(c => char.IsLetterOrDigit(c) || c == '.' ? c : '_').ToArray()).Replace(".", "_");
    }
}
