using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using NhemDangFugBixs.Common.Models;

namespace NhemDangFugBixs.Generators.Emitters;

internal static class ReportEmitter {
    public static string GenerateMarkdown(IEnumerable<ServiceInfo> services, string assemblyName) {
        var sb = new StringBuilder();
        sb.AppendLine($"# DI Registration Report - {assemblyName}");
        sb.AppendLine($"> Generated by NhemDangFugBixs.Tooling v5.0 on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        var grouped = services.GroupBy(s => s.ScopeTypeName ?? s.ScopeName);

        foreach (var group in grouped.OrderBy(g => g.Key)) {
            sb.AppendLine($"## Scope: {group.Key}");
            sb.AppendLine("| Service | Lifetime | Type | Interfaces |");
            sb.AppendLine("| :--- | :--- | :--- | :--- |");

            foreach (var svc in group.OrderBy(s => s.ClassName)) {
                string kind = GetServiceKind(svc);
                string interfaces = svc.InterfaceNames.Length > 0 ? string.Join(", ", svc.InterfaceNames) : "-";
                sb.AppendLine($"| {svc.ClassName} | {svc.Lifetime} | {kind} | {interfaces} |");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    public static string GenerateSource(IEnumerable<ServiceInfo> services, IEnumerable<RootLoggingInfo> rootLogging, string assemblyName) {
        var serviceList = services.ToList();
        var rootLoggingList = rootLogging.ToList();
        var markdown = GenerateMarkdown(serviceList, assemblyName);
        var serviceCount = serviceList.Count;
        var scopes = serviceList
            .Select(GetScopeKey)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(scope => scope, StringComparer.Ordinal)
            .ToList();
        var entries = serviceList
            .OrderBy(s => GetScopeKey(s), StringComparer.Ordinal)
            .ThenBy(s => s.FullName, StringComparer.Ordinal)
            .Select(service => EncodeEntry(service))
            .ToList();
        var consumers = serviceList
            .SelectMany(EncodeConsumers)
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToList();
        var loggerRoots = rootLoggingList
            .OrderBy(info => info.ScopeName, StringComparer.Ordinal)
            .Select(info => $"{info.ScopeName}|{info.HasLoggerFactory}|{info.HasLoggerAdapter}")
            .ToList();
        var loggerConsumers = serviceList
            .SelectMany(EncodeLoggerConsumers)
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace NhemDangFugBixs.Generated.{Sanitize(assemblyName)}");
        sb.AppendLine("{");
        sb.AppendLine("    public static class RegistrationReport");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const int ServiceCount = {serviceCount};");
        sb.AppendLine($"        public const int ScopeCount = {scopes.Count};");
        sb.AppendLine("        public static readonly string[] Scopes = new string[]");
        sb.AppendLine("        {");
        foreach (var scope in scopes) {
            sb.AppendLine($"            \"{Escape(scope)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] Entries = new string[]");
        sb.AppendLine("        {");
        foreach (var entry in entries) {
            sb.AppendLine($"            \"{Escape(entry)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] Consumers = new string[]");
        sb.AppendLine("        {");
        foreach (var consumer in consumers) {
            sb.AppendLine($"            \"{Escape(consumer)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] LoggerRoots = new string[]");
        sb.AppendLine("        {");
        foreach (var loggerRoot in loggerRoots) {
            sb.AppendLine($"            \"{Escape(loggerRoot)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public static readonly string[] LoggerConsumers = new string[]");
        sb.AppendLine("        {");
        foreach (var loggerConsumer in loggerConsumers) {
            sb.AppendLine($"            \"{Escape(loggerConsumer)}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        public const string Markdown = @\"");
        sb.AppendLine(markdown.Replace("\"", "\"\""));
        sb.AppendLine("\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetServiceKind(ServiceInfo svc) {
        if (svc.IsMessagePipeBroker) return "MessageBroker";
        if (svc.IsComponent) return "Component";
        if (svc.IsEntryPoint) return "EntryPoint";
        if (svc.IsInstaller) return "Installer";
        if (svc.IsFactory) return "Factory";
        return "Standard";
    }

    private static string GetScopeKey(ServiceInfo service) {
        if (service.UsesTypeSafeScope && !string.IsNullOrEmpty(service.ScopeTypeName)) {
            return service.ScopeTypeName;
        }

        return service.ScopeName;
    }

    private static string EncodeEntry(ServiceInfo service) {
        return string.Join("|", [
            GetScopeKey(service),
            service.FullName,
            service.Lifetime,
            GetServiceKind(service),
            service.MessageType ?? string.Empty
        ]);
    }

    private static IEnumerable<string> EncodeConsumers(ServiceInfo service) {
        if (!service.Metadata.TryGetValue("MessagePipeConsumers", out var rawValue) || string.IsNullOrWhiteSpace(rawValue)) {
            yield break;
        }

        foreach (var consumer in rawValue.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)) {
            var parts = consumer.Split(new[] { ':' }, 2);
            if (parts.Length != 2) {
                continue;
            }

            yield return string.Join("|", [
                GetScopeKey(service),
                service.FullName,
                parts[0],
                parts[1]
            ]);
        }
    }

    private static IEnumerable<string> EncodeLoggerConsumers(ServiceInfo service) {
        if (!service.Metadata.TryGetValue("LoggerConsumers", out var rawValue) || string.IsNullOrWhiteSpace(rawValue)) {
            yield break;
        }

        foreach (var consumer in rawValue.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)) {
            yield return string.Join("|", [
                GetScopeKey(service),
                service.FullName,
                consumer
            ]);
        }
    }

    private static string Escape(string value) {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string Sanitize(string assemblyName) {
        return new string(assemblyName.Select(c => char.IsLetterOrDigit(c) || c == '.' ? c : '_').ToArray()).Replace(".", "_");
    }
}
