using System.Text;
using System.Linq;
using System.Threading;
using System.Collections.Generic;
using System.IO;
using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using NhemDangFugBixs.Generators.Utils;

namespace NhemDangFugBixs.Generators;

[Generator]
public class StatGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var containers = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (SyntaxNode node, CancellationToken _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
            transform: (GeneratorSyntaxContext ctx, CancellationToken _) => GetStatContainer(ctx)
        ).Where(c => c != null);

        context.RegisterSourceOutput(containers, Execute);
    }

    private static StatContainerInfo? GetStatContainer(GeneratorSyntaxContext context) {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;
        var classSymbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (classSymbol == null) return null;

        var hasAttr = classSymbol.GetAttributes().Any(a => 
            a.AttributeClass?.ToDisplayString() == "NhemDangFugBixs.Runtime.Attributes.StatContainerAttribute");

        if (!hasAttr) return null;

        var stats = new List<StatInfo>();
        foreach (var member in classSymbol.GetMembers()) {
            var statAttr = member.GetAttributes().FirstOrDefault(a => 
                a.AttributeClass?.ToDisplayString() == "NhemDangFugBixs.Runtime.Attributes.StatAttribute");

            if (statAttr == null) continue;

            string typeName = "";
            if (member is IFieldSymbol field) typeName = field.Type.ToDisplayString();
            else if (member is IPropertySymbol prop) typeName = prop.Type.ToDisplayString();

            if (typeName != "float") continue; 

            stats.Add(new StatInfo(member.Name, typeName));
        }

        return new StatContainerInfo(
            classSymbol.ContainingNamespace.ToDisplayString(),
            classSymbol.Name,
            stats
        );
    }

    private static void Execute(SourceProductionContext context, StatContainerInfo container) {
        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using NhemDangFugBixs.Runtime.Models;");
        writer.WriteLine();
        writer.WriteLine($"namespace {container.Namespace};");
        writer.WriteLine();

        using (writer.Block($"public partial class {container.ClassName}")) {
            foreach (var stat in container.Stats) {
                string listName = $"_{stat.Name.ToLower()}Modifiers";
                string dirtyName = $"_{stat.Name.ToLower()}IsDirty";
                string cacheName = $"_{stat.Name.ToLower()}CachedValue";

                writer.WriteLine($"private readonly List<StatModifier> {listName} = new();");
                writer.WriteLine($"private bool {dirtyName} = true;");
                writer.WriteLine($"private float {cacheName};");
                writer.WriteLine();

                using (writer.Block($"public float {stat.Name}Value")) {
                    using (writer.Block("get")) {
                        using (writer.Block($"if ({dirtyName})")) {
                            writer.WriteLine($"{cacheName} = Calculate{stat.Name}();");
                            writer.WriteLine($"{dirtyName} = false;");
                        }
                        writer.WriteLine($"return {cacheName};");
                    }
                }
                writer.WriteLine();

                using (writer.Block($"public void Add{stat.Name}Modifier(StatModifier modifier)")) {
                    writer.WriteLine($"{listName}.Add(modifier);");
                    writer.WriteLine($"{dirtyName} = true;");
                }
                writer.WriteLine();

                using (writer.Block($"public void Remove{stat.Name}Modifier(StatModifier modifier)")) {
                    using (writer.Block($"if ({listName}.Remove(modifier))")) {
                        writer.WriteLine($"{dirtyName} = true;");
                    }
                }
                writer.WriteLine();

                using (writer.Block($"private float Calculate{stat.Name}()")) {
                    writer.WriteLine($"float finalValue = {stat.Name};");
                    writer.WriteLine("float flat = 0;");
                    writer.WriteLine("float percentAdd = 0;");
                    writer.WriteLine("float percentMult = 1;");
                    writer.WriteLine();

                    using (writer.Block($"for (int i = 0; i < {listName}.Count; i++)")) {
                        writer.WriteLine($"var mod = {listName}[i];");
                        using (writer.Block("switch (mod.Type)")) {
                            writer.WriteLine("case ModifierType.Flat: flat += mod.Value; break;");
                            writer.WriteLine("case ModifierType.PercentAdd: percentAdd += mod.Value; break;");
                            writer.WriteLine("case ModifierType.PercentMult: percentMult *= mod.Value; break;");
                        }
                    }
                    writer.WriteLine();
                    writer.WriteLine("return (finalValue + flat) * (1 + percentAdd) * percentMult;");
                }
            }
        }

        context.AddSource($"{container.ClassName}_Stats.g.cs", SourceText.From(stringWriter.ToString(), Encoding.UTF8));
    }

    private class StatContainerInfo {
        public string Namespace { get; }
        public string ClassName { get; }
        public List<StatInfo> Stats { get; }

        public StatContainerInfo(string ns, string className, List<StatInfo> stats) {
            Namespace = ns;
            ClassName = className;
            Stats = stats;
        }
    }

    private class StatInfo {
        public string Name { get; }
        public string Type { get; }

        public StatInfo(string name, string type) {
            Name = name;
            Type = type;
        }
    }
}
