using System;
using System.Collections.Generic;
using System.Text;
using NhemDangFugBixs.Generators.Analyzers;
using NhemDangFugBixs.Generators.Emitters;
using NhemDangFugBixs.Common.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NhemDangFugBixs.Generators;

[Generator]
public class VContainerAutoRegisterGenerator : IIncrementalGenerator {
    // Only emit code for these assemblies (Unity main + Sandbox test)
    private static readonly HashSet<string> AllowedAssemblies = new(StringComparer.OrdinalIgnoreCase) {
        "Assembly-CSharp",
        "DangFugBixs.Sandbox",
        "Shared",
        "Core",
        "Services",
        "Gameplay",
        "Data",
        "Runtime",
        "GameFeel_Shared",
        "GameFeel_Core",
        "GameFeel_Services",
        "GameFeel_Gameplay",
        "GameFeel_Data",
        "GameFeel_Runtime"
    };

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // phase 1: Input Processing 
        var services = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, token) => ClassAnalyzer.ExtractInfo(ctx, token)
                )
            .Where(info => info != null);

        var sceneServices = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, token) => ClassAnalyzer.ExtractSceneInfo(ctx, token)
                )
            .Where(info => info != null);

        // phase 2: Output Generation - combine with compilation to get assembly name
        var combined = services.Collect()
            .Combine(sceneServices.Collect())
            .Combine(context.CompilationProvider);
        
        context.RegisterSourceOutput(combined, Execute);
    }

    private static void Execute(SourceProductionContext context,
        ((System.Collections.Immutable.ImmutableArray<ServiceInfo?> Services, System.Collections.Immutable.ImmutableArray<SceneInjectionInfo?> SceneServices) Data, Compilation Compilation) input) {

        // Guard: only emit for allowed assemblies
        var assemblyName = input.Compilation.AssemblyName ?? "";
        if (!AllowedAssemblies.Contains(assemblyName)) return;

        var validServices = input.Data.Services
            .Where(s => s.HasValue)
            .Select(s => s!.Value)
            .ToList();

        var validSceneServices = input.Data.SceneServices
            .Where(s => s.HasValue)
            .Select(s => s!.Value)
            .ToList();

        if (validServices.Count == 0 && validSceneServices.Count == 0) return;

        var sourceCode = RegistrationEmitter.GenerateSource(validServices, validSceneServices, assemblyName);

        // phase 3: Encapsulation
        var hintName = string.IsNullOrEmpty(assemblyName) ? "VContainerRegistration.g.cs" : $"{assemblyName}.VContainerRegistration.g.cs";
        context.AddSource(hintName, SourceText.From(sourceCode, Encoding.UTF8));
        
        // ALSO: Generate global usings file for NLifetime alias (only once per assembly)
        if (validServices.Count > 0) {
            var globalUsingsCode = GenerateGlobalUsings();
            context.AddSource("NhemDangFugBixs.GlobalUsings.g.cs", SourceText.From(globalUsingsCode, Encoding.UTF8));
        }
    }
    
    private static string GenerateGlobalUsings() {
        return """
// <auto-generated />
// Generated by NhemDangFugBixs.Tooling v3.0
// This file provides convenient aliases for v3.0 type-safe scopes

global using NLifetime = NhemDangFugBixs.Attributes.Lifetime;

""";
    }
}
